
CREATE TABLE IF NOT EXISTS users (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    username             VARCHAR(255) NOT NULL UNIQUE,
    password             VARCHAR(255),
    full_name            VARCHAR(255),
    role                 VARCHAR(50)  NOT NULL,
    auth_provider        VARCHAR(50),
    verified             BOOLEAN      NOT NULL DEFAULT FALSE,
    active               BOOLEAN      NOT NULL DEFAULT TRUE,
    must_change_password BOOLEAN      NOT NULL DEFAULT FALSE,
    created_at           TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS otp_verification (
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email    VARCHAR(255) NOT NULL,
    otp      VARCHAR(10)  NOT NULL,
    verified BOOLEAN      NOT NULL DEFAULT FALSE,
    expiry   TIMESTAMP    NOT NULL
);

CREATE TABLE IF NOT EXISTS client_profile (
    id            UUID         DEFAULT RANDOM_UUID() PRIMARY KEY,
    first_name    VARCHAR(100),
    last_name     VARCHAR(100),
    email_address VARCHAR(255),
    phone         VARCHAR(50),
    address       VARCHAR(255),
    company_name  VARCHAR(255)
);

CREATE TABLE IF NOT EXISTS auditor_profile (
    id                   BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    first_name           VARCHAR(100),
    last_name            VARCHAR(100),
    email_address        VARCHAR(255),
    phone                VARCHAR(50),
    certification_number VARCHAR(100)
);

CREATE TABLE IF NOT EXISTS organisation (
    id                UUID         DEFAULT RANDOM_UUID() PRIMARY KEY,
    client_id         UUID         NOT NULL,
    name              VARCHAR(255) NOT NULL,
    industry          VARCHAR(100),
    fiscal_year_start VARCHAR(5)   NOT NULL DEFAULT '01-01',
    fiscal_year_end   VARCHAR(5)   NOT NULL DEFAULT '12-31',
    default_currency  VARCHAR(10)  NOT NULL DEFAULT 'USD',
    created_at        TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS organisation_member (
    id              UUID        DEFAULT RANDOM_UUID() PRIMARY KEY,
    organisation_id UUID        NOT NULL,
    user_id         BIGINT      NOT NULL,
    role            VARCHAR(20) NOT NULL,
    status          VARCHAR(20) NOT NULL DEFAULT 'ACTIVE',
    joined_at       TIMESTAMP   DEFAULT CURRENT_TIMESTAMP,
    CONSTRAINT uq_org_member UNIQUE (organisation_id, user_id)
);

CREATE TABLE IF NOT EXISTS organisation_currency (
    id              UUID        DEFAULT RANDOM_UUID() PRIMARY KEY,
    organisation_id UUID        NOT NULL,
    currency_code   VARCHAR(10) NOT NULL,
    is_default      BOOLEAN     NOT NULL DEFAULT FALSE,
    CONSTRAINT uq_org_currency UNIQUE (organisation_id, currency_code)
);

CREATE TABLE IF NOT EXISTS organisation_invitation (
    id              UUID         DEFAULT RANDOM_UUID() PRIMARY KEY,
    organisation_id UUID         NOT NULL,
    invited_email   VARCHAR(255) NOT NULL,
    role            VARCHAR(20)  NOT NULL,
    token           VARCHAR(255) NOT NULL UNIQUE,
    status          VARCHAR(20)  NOT NULL DEFAULT 'PENDING',
    invited_by      UUID         NOT NULL,
    expires_at      TIMESTAMP    NOT NULL,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS transactions (
    id              VARCHAR(20)   PRIMARY KEY,
    organisation_id UUID          NOT NULL,
    name            VARCHAR(255)  NOT NULL,
    date            DATE          NOT NULL,
    counterparty    VARCHAR(255),
    donor           VARCHAR(255),
    budget_line     VARCHAR(255),
    amount          NUMERIC(15,2) NOT NULL,
    type            VARCHAR(20)   NOT NULL,
    payment_method  VARCHAR(20)   NOT NULL,
    status          VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    evidence_status VARCHAR(20)   NOT NULL DEFAULT 'MISSING',
    created_by      BIGINT        NOT NULL,
    created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS evidence (
    id              UUID          DEFAULT RANDOM_UUID() PRIMARY KEY,
    organisation_id UUID          NOT NULL,
    transaction_id  VARCHAR(20)   NOT NULL,
    document_name   VARCHAR(255)  NOT NULL,
    folder          VARCHAR(100)  NOT NULL,
    subfolder       VARCHAR(100)  NOT NULL,
    file_upload     VARCHAR(1000) NOT NULL,
    file_type       VARCHAR(50)   NOT NULL,
    notes           TEXT,
    uploaded_by     BIGINT        NOT NULL,
    uploaded_at     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS review_queue (
    id              UUID         DEFAULT RANDOM_UUID() PRIMARY KEY,
    organisation_id UUID         NOT NULL,
    transaction_id  VARCHAR(20)  NOT NULL,
    issue_type      VARCHAR(30)  NOT NULL,
    description     TEXT         NOT NULL,
    status          VARCHAR(20)  NOT NULL DEFAULT 'OPEN',
    flagged_by      VARCHAR(255) NOT NULL,
    resolved_by     BIGINT,
    resolution_note TEXT,
    created_at      TIMESTAMP    DEFAULT CURRENT_TIMESTAMP,
    resolved_at     TIMESTAMP
);

CREATE TABLE IF NOT EXISTS plans (
    tier                      VARCHAR(20)   PRIMARY KEY,
    description               VARCHAR(255)  NOT NULL,
    monthly_price_usd         NUMERIC(10,2) NOT NULL,
    yearly_price_usd          NUMERIC(10,2) NOT NULL,
    max_users                 INT,
    audits_per_month          INT,
    storage_gb                INT           NOT NULL,
    basic_reports              BOOLEAN NOT NULL DEFAULT FALSE,
    email_support              BOOLEAN NOT NULL DEFAULT FALSE,
    advanced_reports           BOOLEAN NOT NULL DEFAULT FALSE,
    audit_trail                BOOLEAN NOT NULL DEFAULT FALSE,
    priority_support            BOOLEAN NOT NULL DEFAULT FALSE,
    custom_workflows            BOOLEAN NOT NULL DEFAULT FALSE,
    compliance_templates        BOOLEAN NOT NULL DEFAULT FALSE,
    api_access                  BOOLEAN NOT NULL DEFAULT FALSE,
    support_24_7                BOOLEAN NOT NULL DEFAULT FALSE,
    sso_saml                    BOOLEAN NOT NULL DEFAULT FALSE,
    dedicated_account_manager   BOOLEAN NOT NULL DEFAULT FALSE,
    custom_integrations         BOOLEAN NOT NULL DEFAULT FALSE,
    sla_guarantee               BOOLEAN NOT NULL DEFAULT FALSE
);

MERGE INTO plans (tier, description, monthly_price_usd, yearly_price_usd, max_users, audits_per_month, storage_gb,
                   basic_reports, email_support, advanced_reports, audit_trail, priority_support, custom_workflows,
                   compliance_templates, api_access, support_24_7, sso_saml, dedicated_account_manager,
                   custom_integrations, sla_guarantee)
KEY (tier)
VALUES
    ('FREE', 'Get started with basic audit management', 0, 0, 2, 5, 1,
     TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    ('STARTER', 'For small teams getting serious about audits', 29, 290, 10, 50, 10,
     TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE, FALSE),
    ('PROFESSIONAL', 'Full-featured audit management for growing organizations', 79, 790, 50, NULL, 100,
     TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, FALSE, FALSE, FALSE, FALSE),
    ('ENTERPRISE', 'Enterprise-grade security and compliance', 199, 1990, NULL, NULL, 1000,
     TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE, TRUE);

CREATE TABLE IF NOT EXISTS subscriptions (
    id              UUID          DEFAULT RANDOM_UUID() PRIMARY KEY,
    organisation_id UUID          NOT NULL,
    plan_tier       VARCHAR(20)   NOT NULL,
    billing_cycle   VARCHAR(10)   NOT NULL,
    status          VARCHAR(20)   NOT NULL DEFAULT 'PENDING',
    start_date      TIMESTAMP,
    end_date        TIMESTAMP,
    created_by      BIGINT,
    created_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at      TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE IF NOT EXISTS payments (
    id                 UUID          DEFAULT RANDOM_UUID() PRIMARY KEY,
    organisation_id    UUID          NOT NULL,
    plan_tier          VARCHAR(20)   NOT NULL,
    billing_cycle      VARCHAR(10)   NOT NULL,
    provider           VARCHAR(10)   NOT NULL,
    status             VARCHAR(10)   NOT NULL DEFAULT 'PENDING',
    usd_amount         NUMERIC(10,2) NOT NULL,
    exchange_rate      NUMERIC(18,6) NOT NULL,
    charged_currency   VARCHAR(3)    NOT NULL,
    charged_amount     NUMERIC(18,2) NOT NULL,
    provider_reference VARCHAR(100)  UNIQUE,
    payer_phone        VARCHAR(20),
    subscription_id    UUID,
    created_by         BIGINT,
    created_at         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
    updated_at         TIMESTAMP     DEFAULT CURRENT_TIMESTAMP
);